#!/bin/bash

#Postinst script to execute after unpacking .deb file
DMI_MODEL="$(cat /sys/class/dmi/id/product_version)"
if [ ! -f "/usr/share/coreboot-updater/models/${DMI_MODEL}" ]
then    
    echo "model '${MODEL}' not found" >&2
    exit 1
fi
#Check if AC adapter is connected
if [ "$(cat /sys/class/power_supply/BAT0/status)" == "Discharging" ]
then
   echo -e "\nStarting post-install firmware update...\n"
   sleep 1
   echo "Please connect your AC adapter for the firmware update to proceed"
   counter=60
   until [ cat /sys/class/power_supply/BAT0/status == "Charging" ]; do
        echo "Waiting for $counter seconds..." 
        ((counter--))
        sleep 1
        [ "$counter" -eq 0 ] && break
   done
fi
sudo chmod +x /usr/share/coreboot-updater/libs/intel-spi/target/release/intel-spi
sudo /usr/share/coreboot-updater/libs/intel-spi/target/release/intel-spi "/usr/share/coreboot-updater/build/${MODEL}/firmware.rom"
exit 0
