#!/bin/bash
deb-systemd-helper stop 'pmc-ltr-ignore.service' >/dev/null || true
deb-systemd-helper disable 'pmc-ltr-ignore.service' >/dev/null || true
rm /lib/systemd/system/pmc-ltr-ignore.service >/dev/null || true
systemctl --system daemon-reload >/dev/null || true
